/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ambiente.Caminhao;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Lucas
 */
public class PatioView extends javax.swing.JFrame {

    /**
     * Creates new form Patio
     */
    public PatioView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelAgua = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPanelAsfalto = new javax.swing.JPanel();
        jPanelPosicaoGateIN = new javax.swing.JPanel();
        jPanelPosicaoGateOUT = new javax.swing.JPanel();
        jPanelRuaGateIn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelAgua.setBackground(new java.awt.Color(33, 100, 163));
        jPanelAgua.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/water.gif"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelAgua.add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/water.gif"))); // NOI18N
        jPanelAgua.add(jLabel2, new java.awt.GridBagConstraints());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/water.gif"))); // NOI18N
        jPanelAgua.add(jLabel3, new java.awt.GridBagConstraints());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/water.gif"))); // NOI18N
        jPanelAgua.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/water.gif"))); // NOI18N
        jPanelAgua.add(jLabel5, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = -100;
        gridBagConstraints.ipady = -900;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanelAgua, gridBagConstraints);

        JPanelAsfalto.setBackground(new java.awt.Color(51, 51, 51));
        JPanelAsfalto.setMinimumSize(new java.awt.Dimension(600, 400));
        JPanelAsfalto.setPreferredSize(new java.awt.Dimension(600, 400));
        JPanelAsfalto.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanelPosicaoGateINLayout = new javax.swing.GroupLayout(jPanelPosicaoGateIN);
        jPanelPosicaoGateIN.setLayout(jPanelPosicaoGateINLayout);
        jPanelPosicaoGateINLayout.setHorizontalGroup(
            jPanelPosicaoGateINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelPosicaoGateINLayout.setVerticalGroup(
            jPanelPosicaoGateINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        JPanelAsfalto.add(jPanelPosicaoGateIN, gridBagConstraints);

        javax.swing.GroupLayout jPanelPosicaoGateOUTLayout = new javax.swing.GroupLayout(jPanelPosicaoGateOUT);
        jPanelPosicaoGateOUT.setLayout(jPanelPosicaoGateOUTLayout);
        jPanelPosicaoGateOUTLayout.setHorizontalGroup(
            jPanelPosicaoGateOUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPosicaoGateOUTLayout.setVerticalGroup(
            jPanelPosicaoGateOUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 150, 20);
        JPanelAsfalto.add(jPanelPosicaoGateOUT, gridBagConstraints);

        jPanelRuaGateIn.setLayout(new javax.swing.BoxLayout(jPanelRuaGateIn, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 50.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        JPanelAsfalto.add(jPanelRuaGateIn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        getContentPane().add(JPanelAsfalto, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatioView().setVisible(true);
            }
        });
    }

    public boolean addCaminhao(int x, int y, Caminhao caminhao) {
//        ImageIcon icon = new ImageIcon("\\images\\caminhaoVazio.jpg"); //Somente esta linha foi alterada
        //icon.setImage(icon.getImage().getScaledInstance(50, 25, 100));
        try {
            BufferedImage bi = ImageIO.read(new File("C:\\Users\\5922496.UNIVALI\\Documents\\NetBeansProjects\\SimPortuarioMA\\SimPortuarioMA\\src\\images\\caminhaoVazio.jpg"));
            Graphics2D g = (Graphics2D) bi.getGraphics();
            g.rotate(Math.toRadians(45), 26, 26);
            g.drawImage(bi, 0, 0, null);
            ImageIcon icon = new ImageIcon(bi);
            icon.setImage(icon.getImage().getScaledInstance(100, 50, 100));
            JLabel truckView = new JLabel(icon);
            truckView.setBounds(x, y, truckView.getWidth(), truckView.getHeight());
            caminhao.setTruckView(truckView);
            truckView.setVisible(true);
            this.getjPanelRuaGateIn().add(truckView);
            this.repaint();
            this.revalidate();
            return true;
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
            return false;
        }
    }

    public JPanel getjPanelRuaGateIn() {
        return jPanelRuaGateIn;
    }

    public JPanel getJPanelAsfalto() {
        return JPanelAsfalto;
    }

    public JPanel getjPanelPosicaoGateIN() {
        return jPanelPosicaoGateIN;
    }

    public JPanel getjPanelPosicaoGateOUT() {
        return jPanelPosicaoGateOUT;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelAsfalto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelAgua;
    private javax.swing.JPanel jPanelPosicaoGateIN;
    private javax.swing.JPanel jPanelPosicaoGateOUT;
    private javax.swing.JPanel jPanelRuaGateIn;
    // End of variables declaration//GEN-END:variables
}
