/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ambiente.Caminhao;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import jdk.nashorn.internal.runtime.arrays.ArrayData;

/**
 *
 * @author Lucas
 */
public class PatioView extends javax.swing.JFrame {

    DefaultListModel<String> filaCaminhoesVector = new DefaultListModel<>();

    /**
     * Creates new form Patio
     */
    public PatioView() {
        initComponents();
        this.setLocationRelativeTo(null);
        setAlwaysOnTop(true);
        filaCaminhoesJList.setModel(filaCaminhoesVector);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelAgua = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JPanelAsfalto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filaCaminhoesJList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelAgua.setBackground(new java.awt.Color(33, 100, 163));
        jPanelAgua.setMaximumSize(new java.awt.Dimension(800, 100));
        jPanelAgua.setMinimumSize(new java.awt.Dimension(800, 100));
        jPanelAgua.setPreferredSize(new java.awt.Dimension(800, 100));
        jPanelAgua.setLayout(new java.awt.GridBagLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/water.gif"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(new java.awt.Dimension(800, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(800, 100));
        jLabel3.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanelAgua.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanelAgua, gridBagConstraints);

        JPanelAsfalto.setBackground(new java.awt.Color(51, 51, 51));
        JPanelAsfalto.setMaximumSize(new java.awt.Dimension(800, 600));
        JPanelAsfalto.setMinimumSize(new java.awt.Dimension(800, 400));
        JPanelAsfalto.setPreferredSize(new java.awt.Dimension(600, 400));
        JPanelAsfalto.setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 300));

        jScrollPane1.setViewportView(filaCaminhoesJList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        JPanelAsfalto.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        getContentPane().add(JPanelAsfalto, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatioView().setVisible(true);
            }
        });
    }

    public synchronized boolean addCaminhaoFila(Caminhao caminhao) {
        try {
            this.filaCaminhoesVector.addElement(caminhao.getPlaca());
            this.filaCaminhoesVector.notify();
            return true;
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
            return false;
        }
    }

    public synchronized boolean removerCaminhaoFila(Caminhao caminhao) {
        try {
            this.filaCaminhoesVector.removeElement(caminhao.getPlaca());
            this.filaCaminhoesVector.notify();
            return true;
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
            return false;
        }
    }

//    private void updateGateList() {
//        DefaultListModel model = new DefaultListModel();
//        for (int i = 0; i < filaCaminhoesVector.size(); i++) {
//            String item = filaCaminhoesVector.get(i);
//            model.addElement(item);
//        }
//        model.no filaCaminhoesJList
//        .setModel(model);
//    }
    public JList<String> getFilaCaminhoesJList() {
        return filaCaminhoesJList;
    }

    public JPanel getJPanelAsfalto() {
        return JPanelAsfalto;
    }

//    public JPanel getjPanelPosicaoGateIN() {
//        return jPanelPosicaoGateIN;
//    }
//    public JPanel getjPanelPosicaoGateOUT() {
//        return jPanelPosicaoGateOUT;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelAsfalto;
    private javax.swing.JList<String> filaCaminhoesJList;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAgua;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
